# dbt_project.yml
name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

# Paths for dbt to find models, snapshots, seeds, etc.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  my_new_project:

    # Orders folder models materialized as tables
    orders:
      +materialized: table

    # All other models not in orders/ will default to view
